// display input ko pakdo
let display = document.getElementById("display");

// sabhi calculator buttons ko pakdo
let buttons = document.querySelectorAll(".js");

// yeh variable calculation store karega
let expression = "";

// har button par same kaam (same JS logic)
buttons.forEach(btn => {

    btn.addEventListener("click", () => {

        let value = btn.innerText;

        if (value === "AC") {
            expression = "";
            display.value = "";

        } else if (value === "C") {
            expression = expression.slice(0, -1);
            display.value = expression;

        } else if (value === "=") {
            try {
                expression = eval(expression);
                display.value = expression;
            } catch {
                display.value = "Error";
                expression = "";
            }

        } else {
            expression += value;
            display.value = expression;
        }
    });

});
